export const URL_HOME = "/";
export const URL_LOGIN = "/login";
export const URL_FORGET_LOGIN = "/forget-login";
export const URL_RESET_PASSWORD = `/reset-password`;
export const URL_FORGET_EMAIL = "/forget-email";
export const URL_PASSWORD_MODIFIED = "/password-modified";
export const URL_ADMIN_HOME = "/admin";
export const URL_REGISTER = "/register";
export const URL_REGISTER_LAST = "/register-submitted";
export const URL_MAIL_VERIFIED = "verify-email/:signedToken/:_id";
export const URL_LIST = "/simple-list";
export const URL_CREATE = "/create";
export const URL_HISTORICAL = "/historical";
export const URL_AVATAR = "/avatar";
export const URL_FOOTER = "/";
export const URL_HOMEPAGE = "/homePage";
export const URL_PROFIL = "/profil";
export const URL_FAQ = "/faq";
export const URL_CONTACT = "/contact";
export const URL_PROFILEPREFS = "/profilePrefs";
export const URL_TRAJETS = "/trajets";
export const URL_CARTE = "/carte";
export const URL_DELETE_ACCOUNT = "/deleteAccount";
export const URL_DELETE_ACCOUNT_MODAL = "/deleteAccountModal";

export const URL_SEARCH = `/search`;
export const URL_TRAJET_CREATE = `/createTrajet`;

export const URL_CHAT_SOCKET ='/chat';